# Generated by Django 3.0.5 on 2020-06-03 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0002_auto_20200604_0050'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='downvotes',
            field=models.ManyToManyField(related_name='downvoters', to='action.Action'),
        ),
        migrations.AddField(
            model_name='user',
            name='upvotes',
            field=models.ManyToManyField(related_name='upvoters', to='action.Action'),
        ),
    ]
